- name: Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ fromJSON(secrets.FTP_CONFIG).server1.server }}
          username: ${{ fromJSON(secrets.FTP_CONFIG).server1.username }}
          password: ${{ fromJSON(secrets.FTP_CONFIG).server1.password }}
          protocol: ftps
          port: 21
          security: loose
          # ▼ 実際にアップロードする場所（有効）
          server-dir: ./blockworks.jp/public_html/test-dayo/

          # ▼ 将来リポジトリ名と同じフォルダにしたい場合のメモ（無効化）
          # server-dir: ./blockworks.jp/public_html/${{ github.event.repository.name }}/

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**